<a href="https://colab.research.google.com/github/UsmanArif169/Scikit-learn-Tutorial/blob/main/scikit_learn_one_hot_encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('/content/onedata.xlsx')
df.head()

   buyer  fruits  gender  value
0    ali   apple    male      2
1   noor   mango    male      3
2  wajid  orange  female      4
3  karim  banana    male      4

# **Using Python**

In [ ]:
pd.get_dummies(data = df, columns = ['buyer','fruits','gender'])

,value,buyer_ali,buyer_karim,buyer_noor,buyer_wajid,fruits_apple,fruits_banana,fruits_mango,fruits_orange,gender_female,gender_male
0,2,True,False,False,False,True,False,False,False,False,True
1,3,False,False,True,False,False,False,True,False,False,True
2,4,False,False,False,True,False,False,False,True,True,False
3,4,False,True,False,False,False,True,False,False,False,True

In [ ]:
pd.get_dummies(data = df, columns = ['buyer','fruits','gender'], dtype = int, drop_first ='first')

,value,buyer_karim,buyer_noor,buyer_wajid,fruits_banana,fruits_mango,fruits_orange,gender_male
0,2,0,0,0,0,0,0,1
1,3,0,1,0,0,1,0,1
2,4,0,0,1,0,0,1,0
3,4,1,0,0,1,0,0,1

# **Using Sklearn OneHotEncoder**

In [ ]:
# We use this no natural relationship between categorical column

from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop = 'first', dtype = int, sparse_output= False)
df_trf=ohe.fit_transform(df[['buyer','fruits','gender']])

In [ ]:
df_trf

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1]])

In [ ]:
cols=ohe.get_feature_names_out()

In [ ]:
cols

array(['buyer_karim', 'buyer_noor', 'buyer_wajid', 'fruits_banana',
       'fruits_mango', 'fruits_orange', 'gender_male'], dtype=object)